FROM registry.opensuse.org/opensuse/tumbleweed:latest

RUN zypper ar -G https://download.opensuse.org/repositories/devel:/openQA/openSUSE_Tumbleweed devel-openqa && \
    true

RUN zypper -n ref && zypper -n install git \
        os-autoinst-devel openQA-devel \
        expect \
        perl-Text-Markdown \
        python3-pytest \
        python3-virtualenv \
        nodejs npm \
    && true

RUN zypper -n install vi git wget curl ack zsh tmux tmate tree perl-doc jq

