FROM registry.opensuse.org/opensuse/leap:15.4

RUN zypper ar -G https://download.opensuse.org/repositories/devel:/openQA/15.4 devel-openqa && \
    zypper ar -G https://download.opensuse.org/repositories/devel:/openQA:/Leap:/15.4/15.4/ devel-openqa-leap

RUN zypper -n ref && zypper -n install git vi \
        os-autoinst-devel openQA-devel \
    && true

RUN zypper -n install ack zsh

